[phases.setup]
nixPkgs = ["python311", "nodejs_18"]

[phases.install]
cmds = ["cd web-app && npm install", "pip install -r web-app/requirements.txt"]

[phases.build]
cmds = ["cd web-app && npm run build"]

[start]
cmd = "cd web-app && gunicorn --worker-class eventlet -w 1 flask_api:app --bind 0.0.0.0:$PORT"
